---
title: "Lecture13_Notes"
author: "Wenjie Qi"
date: "2021/11/9"
output: html_document
---

```{r}
library(tidyverse)
```

# Examples of statistical estimation

## Example 1
```{r}
set.seed(2)
num_trials <- 1000
sample_size <- 30
q <- 0.3

simulation_df <- data.frame(trial=seq(num_trials)) %>%
  mutate(simulation=map(.x=trial, .f=~rbinom(sample_size, 1, q))) %>%
  # simulate sequences of Bernoulli random variables
  mutate(sample_mean=map_dbl(.x=simulation, .f=mean))
  # compute the sample means

#simulation_df

ggplot() + labs(x="Mean", y="Density") + theme_bw() + 
  geom_density(data = simulation_df, aes(x=sample_mean, color="Sample", 
                                         linetype="Sample")) + 
  # kernel density plot of sample means
  geom_vline(aes(xintercept=q, color="Population",
                 linetype="Population")) + 
  # vertical line displaying population mean
  scale_color_manual(name="Legend", 
                     values=c("Sample"="red", "Population"="blue")) +
  scale_linetype_manual(name="Legend",
                        values=c("Sample"="solid", "Population"="dashed"))

```


```{r}
set.seed(3)
num_trials_per_sample_size <- 10
max_sample_size <- 10000
q <- 0.3

sim_by_n_df <- crossing(trial=seq(num_trials_per_sample_size),
                        sample_size=seq(to=sqrt(max_sample_size), by=0.1)**2) %>%
  # create data frame of all pairs of sample_size and trial
  mutate(simulation=pmap(.l=list(trial, sample_size), .f=~rbinom(.y, 1, q))) %>%
  # simulate sequences of Bernoulli random variables
  mutate(sample_mean=map_dbl(.x=simulation, .f=mean))
  # compute the sample means

# sim_by_n_df

ggplot() + labs(x="Sample size", y="Mean") + theme_bw() +
  geom_point(data=sim_by_n_df,
             aes(x=sample_size, y=sample_mean, color="Sample",
                 linetype="Sample"), size=0.1) +
  # Scatter plot of sample means
  geom_hline(aes(yintercept=q, color="Population", 
                 linetype="Population"), size=0.1) +
  # horizontal line displaying population mean
  scale_color_manual(name="Legend",
                     values=c("Sample"="blue", "Population"="red")) +
  scale_linetype_manual(name="Legend",
                        values=c("Sample"="dashed", "Population"="solid")) +
  scale_x_sqrt()

```

## Example 2

```{r}
set.seed(0)
num_trials <- 1000
sample_size <- 30
mu <- 1
sigma_sqr <- 3

simulation_df <- data.frame(trial=seq(num_trials)) %>%
  mutate(simulation=map(.x=trial,
                        .f=~rnorm(sample_size, mean=mu, sd=sqrt(sigma_sqr)))) %>%
  # simulate sequences of Gaussian random variables
  mutate(sample_var=map_dbl(.x=simulation, .f=var))


  ggplot() + labs(x="Variance", y="Density") + theme_bw() +
    geom_density(data=simulation_df,
                 aes(x=sample_var, color="Sample")) +
    #kernel density plot of sample variances
    geom_vline(aes(xintercept=sigma_sqr, color="Population",
                   linetype="Population")) +
    #vertical line displaying population mean
    
    scale_color_manual(name = "Legend",
                       values = c("Sample"="red", "Population"="blue")) +
    scale_linetype_manual(name = "Legend",
                          values = c("Sample"="solid", "Population"="dashed"))
```


```{r}
set.seed(0)
num_trials_per_sample_size <- 10
max_sample_size <- 10000
mu <- 1
sigma_sqr <- 3

sim_by_n_df <- crossing(trial=seq(num_trials_per_sample_size),
                        sample_size=seq(to=sqrt(max_sample_size), by=0.1)**2) %>%
  # create data frame of all pairs of sample_size and trial
  mutate(simulation=pmap(.l=list(trial, sample_size),
                         .f=~rnorm(.y, mean=mu, sd=sqrt(sigma_sqr)))) %>%
  #simulate sequences of Gaussian random variables
  mutate(sample_var=map_dbl(.x=simulation, .f=var))
  # compute the sample variance

ggplot() + labs(x="Sample size", y="Variance") + theme_bw() +
  geom_point(data=sim_by_n_df,
             aes(x=sample_size, y=sample_var, color="Sample",
                 linetype="Sample"), size=0.1) +
  # scatter plot of sample variance
  geom_hline(aes(yintercept=sigma_sqr, color="Population",
                 linetype="Population"), size=1) +
  # horizontal line displaying population variance
  scale_color_manual(name = "Legend",
                     values = c("Sample"="blue", "Population"="red")) +
  scale_linetype_manual(name = "Legend",
                        values = c("Sample"= "dashed", "Population"="solid")) +
  scale_x_sqrt()
```

# Cauchy distribution

```{r}
set.seed(0)
num_trials_per_sample_size <- 10
max_sample_size <- 10000
theta <- 1

sim_by_n_df <- crossing(trial=seq(num_trials_per_sample_size),
                        sample_size=seq(to=sqrt(max_sample_size), by=0.1)**2) %>%
  # create data frame of all pairs of sample_size and trial
  mutate(simulation=pmap(.l=list(trial, sample_size), .f=~rcauchy(.y, location=theta))) %>%
  # simulate sequences of Cauchy random variables
  mutate(sample_mean=map_dbl(.x=simulation, .f=mean))
  # compute the sample means

sim_by_n_df %>%
  head(3)

ggplot() + labs(x="Sample size", y="Sample mean") + theme_bw() +
  geom_point(data=sim_by_n_df,
             aes(x=sample_size, y=sample_mean, color="Sample mean",
                 linetype="Sample mean"), size=0.1) +
  geom_hline(aes(yintercept=theta, color="Location parameter",
             linetype="Location parameter"), size=1) +
  scale_color_manual(name = "Legend",
                     values = c("Sample mean"="blue", "Location parameter"="red")) +
  scale_linetype_manual(name = "Legend",
                        values = c("Sample mean"="dashed", "Location parameter"="solid")) +
  xlim(c(0, 10000)) +
  ylim(c(-10, 10))
```














